### ISSUE TITLE
Fixing other Platinum Engine games

### ISSUE THREAD

**Issue by Keith94** [Francesco149/nier_uncapped#1]
Other games running on the same engine as Nier ([Platinum Engine](http://pcgamingwiki.com/wiki/Engine:Platinum_Engine)) are also capped at 60 FPS:

* Metal Gear Rising: Revengeance
* The Legend of Korra
* Transformers: Devastation

Maybe you would know how to unlock the frame rate in these games as well (if they use the same method)?

**Comment by Francesco149** [comment]
I'd have to have the games and poke around for a while. It's likely that they would be uncappable with a similar or same method yeah, but I'd still have to have the game, scan the memory for the code, etc. I'm not gonna do that, but other coders can probably try - my code includes comments with byte patterns to scan for the fps capping code.

**Comment by Keith94** [comment]
Cool man, hopefully someone is willing to find the time to fix these games some day. :)
